MNT Use GitHub Actions CI
silverstripe/cwp-agencyextensions pull request #74
Opened 2022-07-05 05:25 UTC by emteknetnz

Issue https://github.com/silverstripe/gha-ci/issues/11<br /><br />Workflow run https://github.com/creative-commoners/cwp-agencyextensions/actions?query=branch%3Apulls%2F2.6%2Fmodule-standards

2022-07-15 04:40 UTC, GuySartorelli requested changes

2022-07-15 04:40 UTC, GuySartorelli commented on composer.json
> +        "silverstripe/auditor": "<2.4.0"
Why is this conflict added? If it's the same issue that we've dealt with in PRs that were merged already, please update to the correct version.

2022-07-15 04:40 UTC, GuySartorelli commented on composer.json
>          "squizlabs/php_codesniffer": "^3"
Travis config requires fulltextsearch - should we add that here?

2022-07-17 21:43 UTC, emteknetnz commented on composer.json
> +        "silverstripe/auditor": "<2.4.0"
Updated

2022-07-17 21:44 UTC, emteknetnz commented on composer.json
>          "squizlabs/php_codesniffer": "^3"
There's no skipped unit tests and there's no mention of fulltextsearch in the codebase, so I think we can safely omit it

2022-07-17 22:19 UTC, GuySartorelli approved these changes

2022-07-17 22:19 UTC, merged